# Generated by Django 4.2.16 on 2026-09-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador estável usado pelo seed do cardápio para não duplicar itens', max_length=160, null=True, unique=True),
        ),
    ]
